const Sequelize = require('sequelize');

module.exports = function(db) {
    var table = db.define('tblDonHang', {
        ID: {
            type: Sequelize.BIGINT,
            primaryKey: true,
            autoIncrement: true
        },
        IDYeuCau: Sequelize.BIGINT,
        IDYeuCauChiTiet: Sequelize.BIGINT,
        IDLoaiHinhVanChuyen: Sequelize.BIGINT,
        IDNhaXe: Sequelize.BIGINT,
        IDNhanVienCSKH: Sequelize.BIGINT,
        IDLoaiVo: Sequelize.BIGINT,
        IDHangTau: Sequelize.BIGINT,
        IDLoaiXe: Sequelize.BIGINT,
        IDXe: Sequelize.BIGINT,
        IDNhanVienKH: Sequelize.BIGINT,
        MaDoiChieu: Sequelize.STRING,
        SoDonHang: Sequelize.STRING,
        GiaCuocThu: Sequelize.STRING,
        GiaCuocChi: Sequelize.STRING,
        GioDong: Sequelize.STRING,
        GioTra: Sequelize.STRING,
        GhiChu: Sequelize.STRING,
        ChiPhiPhatSinhThu: Sequelize.FLOAT,
        ChiPhiPhatSinhChi: Sequelize.FLOAT,
        TongTienThu: Sequelize.STRING,
        TongTienChi: Sequelize.STRING,
        TrangThai: Sequelize.STRING,
        SoLuongVo: Sequelize.STRING,
        TrongLuong: Sequelize.STRING,
        NoiDong: Sequelize.STRING,
        IDDiaDiemDong: Sequelize.STRING,
        DiaDiemDong: Sequelize.STRING,
        NoiTra: Sequelize.STRING,
        IDDiaDiemTra: Sequelize.STRING,
        DiaDiemTra: Sequelize.STRING,
        PheDuyet: Sequelize.STRING,
        SoContainer: Sequelize.STRING,
        SoChi: Sequelize.STRING,
        NguoiLayHang: Sequelize.STRING,
        SDTNguoiLay: Sequelize.STRING,
        GhiChuLay: Sequelize.STRING,
        NguoiTraHang: Sequelize.STRING,
        SDTNguoiTra: Sequelize.STRING,
        GhiChuTra: Sequelize.STRING,
        GhiChuChiPhi: Sequelize.STRING,
        EditDate: Sequelize.STRING,
        CreateDate: Sequelize.STRING,
        HanThu: Sequelize.STRING,
        HanTra: Sequelize.STRING,
        BienSoXe: Sequelize.STRING,
        TenLaiXe: Sequelize.STRING,
        SDTLaiXe: Sequelize.STRING,
        COM: Sequelize.STRING,
        COMPhatSinh: Sequelize.STRING,
        IDDMXeCongTy: Sequelize.STRING,
        CuocVanChuyen: Sequelize.STRING,
        PhiDichVuThongQuan: Sequelize.STRING,
        PhiThuHo: Sequelize.STRING,
        PhiPhatSinh: Sequelize.STRING,
        TienDau: Sequelize.STRING,
        SoKmVanHanh: Sequelize.STRING,
        SoDauVanHanh: Sequelize.STRING,
        GiaDau: Sequelize.STRING,
        TienDauPhuTroi: Sequelize.STRING,
        SoDauPhuTroi: Sequelize.STRING,
        TienAnTienDuong: Sequelize.STRING,
        TienLuongChuyen: Sequelize.STRING,
        PhiDinhMuc: Sequelize.STRING,
        PhiTraHo: Sequelize.STRING,
        IDDonHang: Sequelize.STRING,
        TrangThaiCho: Sequelize.STRING,
        ConfirmKH: Sequelize.STRING,
        ConfirmNX: Sequelize.STRING,
        COMPhatSinh: Sequelize.STRING,
        TongCOM: Sequelize.STRING,
        TongCuocChi: Sequelize.STRING,
        IDDMXeCongTy: Sequelize.STRING,
        CuocVanChuyen: Sequelize.STRING,
        PhiDichVuThongQuan: Sequelize.STRING,
        PhiThuHo: Sequelize.STRING,
        PhiPhatSinh: Sequelize.STRING,
        TienDau: Sequelize.STRING,
        SoKmVanHanh: Sequelize.STRING,
        SoDauVanHanh: Sequelize.STRING,
        GiaDau: Sequelize.STRING,
        TienDauPhuTroi: Sequelize.STRING,
        SoDauPhuTroi: Sequelize.STRING,
        TienAnTienDuong: Sequelize.STRING,
        TienLuongChuyen: Sequelize.STRING,
        PhiDinhMuc: Sequelize.STRING,
        PhiTraHo: Sequelize.STRING,
        IDDonHang: Sequelize.STRING,
        TrangThaiCho: Sequelize.STRING,
        ConfirmKH: Sequelize.BOOLEAN,
        ConfirmNX: Sequelize.BOOLEAN,
        NgayGui: Sequelize.STRING,
        FilterState: Sequelize.STRING,
        // DoiTuong: Sequelize.STRING,
        // DBName: Sequelize.STRING,
        // ChuHang: Sequelize.STRING,
        // Type: Sequelize.STRING,
        // YeuCauDongBo: Sequelize.STRING,
        ThongBaoDiaDiem: Sequelize.BOOLEAN,
        ThongBaoChiPhi: Sequelize.BOOLEAN,
        ThongBaoNVTDKHSuaCP: Sequelize.BOOLEAN,
        // ThongBaoHoanThanh: Sequelize.STRING,
        IDDonHangChinhSua: Sequelize.BIGINT,
        // DonHangChinhSua: Sequelize.STRING,
        // AttachImage: Sequelize.STRING,
        // KhachHang: Sequelize.STRING,
        // DonHangs: Sequelize.STRING,
        // NhanVienCSKH: Sequelize.STRING,
        // NhanVienKH: Sequelize.STRING,
        // YeuCauChiTiet: Sequelize.STRING,
        // YeuCau: Sequelize.STRING,
        // DiaDiemDongs: Sequelize.STRING,
        // DiaDiemTras: Sequelize.STRING,
        // LoaiHinhVanChuyen: Sequelize.STRING,
        // NhaXe: Sequelize.STRING,
        // XeCongTy: Sequelize.STRING,
        // LoaiXe: Sequelize.STRING,
        // LoaiVo: Sequelize.STRING,
        // HangTau: Sequelize.STRING,
        // ChiPhiChiDonHangs: Sequelize.STRING,
        // ChiPhiThuDonHangs: Sequelize.STRING,
        // ChiPhiKhacChoXeCTs: Sequelize.STRING,
        // DoanhThuKhacChoXeCTs: Sequelize.STRING,
    });

    return table;
}